# Generated by Django 2.0.5 on 2018-06-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('street', models.CharField(max_length=64, verbose_name='Street')),
                ('house_number', models.CharField(max_length=32, verbose_name='HouseNumber')),
                ('flat_number', models.SmallIntegerField(verbose_name='FlatNumber')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(max_length=128, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=32, verbose_name='Surname'),
        ),
    ]
