# Generated by Django 2.0.5 on 2018-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(null=True, upload_to='photos', verbose_name='Photo'),
        ),
    ]
