# Generated by Django 2.0.5 on 2018-06-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_auto_20180617_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo/%Y/%m/%D', verbose_name='Photo'),
        ),
    ]
