# Generated by Django 2.0.5 on 2018-06-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0007_auto_20180619_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_email', models.CharField(max_length=32, verbose_name='HomeEmail')),
                ('work_email', models.CharField(max_length=32, verbose_name='WorkEmail')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='box.Person', verbose_name='Person')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_phone', models.CharField(max_length=32, verbose_name='HomePhone')),
                ('work_phone', models.CharField(max_length=32, verbose_name='WorkPhone')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='box.Person', verbose_name='Person')),
            ],
        ),
    ]
