# Generated by Django 2.0.5 on 2018-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0008_email_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='home_email',
            field=models.CharField(max_length=32, null=True, verbose_name='HomeEmail'),
        ),
        migrations.AlterField(
            model_name='email',
            name='work_email',
            field=models.CharField(max_length=32, null=True, verbose_name='WorkEmail'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='home_phone',
            field=models.CharField(max_length=32, null=True, verbose_name='HomePhone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='work_phone',
            field=models.CharField(max_length=32, null=True, verbose_name='WorkPhone'),
        ),
    ]
