# Generated by Django 2.0.5 on 2018-06-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0010_auto_20180619_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ManyToManyField(to='box.Person', verbose_name='Group')),
            ],
        ),
    ]
