# Generated by Django 2.0.5 on 2018-06-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0011_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='-', max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='person',
            field=models.ManyToManyField(null=True, to='box.Person', verbose_name='Group'),
        ),
    ]
