# Generated by Django 2.0.5 on 2018-06-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0012_auto_20180619_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='photos/None/no-img.jpg', upload_to='photos/', verbose_name='Photo'),
        ),
    ]
